// Generated by CoffeeScript 1.12.7
(function() {
  var add;

  add = function(x, y) {
    if (x == null) {
      x = 4;
    }
    if (y == null) {
      y = 3;
    }
    return x + y;
  };

  add(5);

}).call(this);
